// Code generated by logcopter-gen; DO NOT EDIT.

package verbs

import logcopter "github.com/go-go-golems/logcopter/pkg/logcopter"

var log = logcopter.Package("go-go-golems.loupedeck.cmd.loupedeck.cmds.verbs")
