// Code generated by logcopter-gen; DO NOT EDIT.

package env

import logcopter "github.com/go-go-golems/logcopter/pkg/logcopter"

var log = logcopter.Package("go-go-golems.loupedeck.runtime.js.env")
