// Code generated by logcopter-gen; DO NOT EDIT.

package module_gfx

import logcopter "github.com/go-go-golems/logcopter/pkg/logcopter"

var log = logcopter.Package("go-go-golems.loupedeck.runtime.js.module_gfx")
